version: "3"
services:
  traefik:
    build: traefik
    image: traefik
    container_name: traefik
    networks:
      traefik:
        ipv4_address: 172.10.0.10
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./ca:/usr/local/share/ca-certificates:ro"
    restart: always
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.test
    depends_on:
      - pebble
    
  pebble:
    build: pebble
    image: pebble
    container_name: pebble
    volumes:
        - "./ca:/var/pebble/certs/ca"
    networks:
        traefik:
          ipv4_address: 172.10.0.5
    ports:
        - 443
    restart: always
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true
