logLevel = "INFO"
defaultEntryPoints = ["http", "https"]
rootCAs = ["/usr/local/share/ca-certificates/cert.pem"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
storage = "/var/run/acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
caServer = "https://pebble/dir"
  [acme.httpChallenge]
  entryPoint="http"


[docker]
domain = "test"
watch = true
network = "traefik"

